// Code generated by MockGen. DO NOT EDIT.
// Source: url_repository_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	repository "github.com/anoriar/shortener/internal/shortener/dto/repository"
	entity "github.com/anoriar/shortener/internal/shortener/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockURLRepositoryInterface is a mock of URLRepositoryInterface interface.
type MockURLRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryInterfaceMockRecorder
}

// MockURLRepositoryInterfaceMockRecorder is the mock recorder for MockURLRepositoryInterface.
type MockURLRepositoryInterfaceMockRecorder struct {
	mock *MockURLRepositoryInterface
}

// NewMockURLRepositoryInterface creates a new mock instance.
func NewMockURLRepositoryInterface(ctrl *gomock.Controller) *MockURLRepositoryInterface {
	mock := &MockURLRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepositoryInterface) EXPECT() *MockURLRepositoryInterfaceMockRecorder {
	return m.recorder
}

// AddURL mocks base method.
func (m *MockURLRepositoryInterface) AddURL(url *entity.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddURL", url)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddURL indicates an expected call of AddURL.
func (mr *MockURLRepositoryInterfaceMockRecorder) AddURL(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddURL", reflect.TypeOf((*MockURLRepositoryInterface)(nil).AddURL), url)
}

// AddURLBatch mocks base method.
func (m *MockURLRepositoryInterface) AddURLBatch(ctx context.Context, urls []entity.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddURLBatch", ctx, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddURLBatch indicates an expected call of AddURLBatch.
func (mr *MockURLRepositoryInterfaceMockRecorder) AddURLBatch(ctx, urls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddURLBatch", reflect.TypeOf((*MockURLRepositoryInterface)(nil).AddURLBatch), ctx, urls)
}

// Close mocks base method.
func (m *MockURLRepositoryInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockURLRepositoryInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockURLRepositoryInterface)(nil).Close))
}

// DeleteURLBatch mocks base method.
func (m *MockURLRepositoryInterface) DeleteURLBatch(ctx context.Context, shortURLs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteURLBatch", ctx, shortURLs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteURLBatch indicates an expected call of DeleteURLBatch.
func (mr *MockURLRepositoryInterfaceMockRecorder) DeleteURLBatch(ctx, shortURLs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLBatch", reflect.TypeOf((*MockURLRepositoryInterface)(nil).DeleteURLBatch), ctx, shortURLs)
}

// FindURLByOriginalURL mocks base method.
func (m *MockURLRepositoryInterface) FindURLByOriginalURL(ctx context.Context, originalURL string) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindURLByOriginalURL", ctx, originalURL)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindURLByOriginalURL indicates an expected call of FindURLByOriginalURL.
func (mr *MockURLRepositoryInterfaceMockRecorder) FindURLByOriginalURL(ctx, originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindURLByOriginalURL", reflect.TypeOf((*MockURLRepositoryInterface)(nil).FindURLByOriginalURL), ctx, originalURL)
}

// FindURLByShortURL mocks base method.
func (m *MockURLRepositoryInterface) FindURLByShortURL(shortURL string) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindURLByShortURL", shortURL)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindURLByShortURL indicates an expected call of FindURLByShortURL.
func (mr *MockURLRepositoryInterfaceMockRecorder) FindURLByShortURL(shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindURLByShortURL", reflect.TypeOf((*MockURLRepositoryInterface)(nil).FindURLByShortURL), shortURL)
}

// GetURLsByQuery mocks base method.
func (m *MockURLRepositoryInterface) GetURLsByQuery(ctx context.Context, urlQuery repository.Query) ([]entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLsByQuery", ctx, urlQuery)
	ret0, _ := ret[0].([]entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLsByQuery indicates an expected call of GetURLsByQuery.
func (mr *MockURLRepositoryInterfaceMockRecorder) GetURLsByQuery(ctx, urlQuery interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLsByQuery", reflect.TypeOf((*MockURLRepositoryInterface)(nil).GetURLsByQuery), ctx, urlQuery)
}

// Ping mocks base method.
func (m *MockURLRepositoryInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockURLRepositoryInterfaceMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockURLRepositoryInterface)(nil).Ping), ctx)
}

// UpdateIsDeletedBatch mocks base method.
func (m *MockURLRepositoryInterface) UpdateIsDeletedBatch(ctx context.Context, shortURLs []string, isDeleted bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIsDeletedBatch", ctx, shortURLs, isDeleted)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIsDeletedBatch indicates an expected call of UpdateIsDeletedBatch.
func (mr *MockURLRepositoryInterfaceMockRecorder) UpdateIsDeletedBatch(ctx, shortURLs, isDeleted interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIsDeletedBatch", reflect.TypeOf((*MockURLRepositoryInterface)(nil).UpdateIsDeletedBatch), ctx, shortURLs, isDeleted)
}
