// Code generated by MockGen. DO NOT EDIT.
// Source: delete_user_urls_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDeleteUserURLsInterface is a mock of DeleteUserURLsInterface interface.
type MockDeleteUserURLsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteUserURLsInterfaceMockRecorder
}

// MockDeleteUserURLsInterfaceMockRecorder is the mock recorder for MockDeleteUserURLsInterface.
type MockDeleteUserURLsInterfaceMockRecorder struct {
	mock *MockDeleteUserURLsInterface
}

// NewMockDeleteUserURLsInterface creates a new mock instance.
func NewMockDeleteUserURLsInterface(ctrl *gomock.Controller) *MockDeleteUserURLsInterface {
	mock := &MockDeleteUserURLsInterface{ctrl: ctrl}
	mock.recorder = &MockDeleteUserURLsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteUserURLsInterface) EXPECT() *MockDeleteUserURLsInterfaceMockRecorder {
	return m.recorder
}

// DeleteUserURLs mocks base method.
func (m *MockDeleteUserURLsInterface) DeleteUserURLs(ctx context.Context, userID string, shortURLs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserURLs", ctx, userID, shortURLs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserURLs indicates an expected call of DeleteUserURLs.
func (mr *MockDeleteUserURLsInterfaceMockRecorder) DeleteUserURLs(ctx, userID, shortURLs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserURLs", reflect.TypeOf((*MockDeleteUserURLsInterface)(nil).DeleteUserURLs), ctx, userID, shortURLs)
}
