#!/bin/bash

# Define the output directory
OUTPUT_DIR=proto/generated

# Create the output directory if it does not exist
if [ ! -d "$OUTPUT_DIR" ]; then
  mkdir "$OUTPUT_DIR"
fi

# Generate the protocol buffer and gRPC code
protoc --go_out="$OUTPUT_DIR" --go-grpc_out="$OUTPUT_DIR" proto/shortener.proto