// Code generated by MockGen. DO NOT EDIT.
// Source: short_url_generator_interface.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortURLGeneratorInterface is a mock of ShortURLGeneratorInterface interface.
type MockShortURLGeneratorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLGeneratorInterfaceMockRecorder
}

// MockShortURLGeneratorInterfaceMockRecorder is the mock recorder for MockShortURLGeneratorInterface.
type MockShortURLGeneratorInterfaceMockRecorder struct {
	mock *MockShortURLGeneratorInterface
}

// NewMockShortURLGeneratorInterface creates a new mock instance.
func NewMockShortURLGeneratorInterface(ctrl *gomock.Controller) *MockShortURLGeneratorInterface {
	mock := &MockShortURLGeneratorInterface{ctrl: ctrl}
	mock.recorder = &MockShortURLGeneratorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURLGeneratorInterface) EXPECT() *MockShortURLGeneratorInterfaceMockRecorder {
	return m.recorder
}

// GenerateShortURL mocks base method.
func (m *MockShortURLGeneratorInterface) GenerateShortURL() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateShortURL")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateShortURL indicates an expected call of GenerateShortURL.
func (mr *MockShortURLGeneratorInterfaceMockRecorder) GenerateShortURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateShortURL", reflect.TypeOf((*MockShortURLGeneratorInterface)(nil).GenerateShortURL))
}
