name: coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-and-generate-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          coverage=$(go tool cover -func=coverage.out | grep total: | grep -Eo '[0-9]+\.[0-9]+')
          echo "Total coverage: $coverage%"
          echo "::set-output name=coverage::$coverage" # Set output for further use

      - name: Create coverage badge
        run: |
          coverage=$(echo ${{ steps.test-and-display-coverage.outputs.coverage }})
          curl -o coverage.svg "https://img.shields.io/badge/coverage-$coverage%25-brightgreen"

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: coverage.svg